# Generated by Django 5.2 on 2025-04-10 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_product_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
