# Generated by Django 5.2 on 2025-04-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_product_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='email',
            field=models.EmailField(default='seller@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='product',
            name='photo1',
            field=models.ImageField(default='product_photos/default.jpg', upload_to='product_photos/'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo2',
            field=models.ImageField(default='product_photos/default.jpg', upload_to='product_photos/'),
        ),
        migrations.AddField(
            model_name='product',
            name='quality',
            field=models.CharField(default='Good', max_length=100),
        ),
    ]
